image: "hub.docker.com/r/jamesdbloom/docker-java8-maven"

stages:
  - docker_images
  - system_tests
  - unit_tests
  - integration_tests
  - deploy


before_script:
  - chmod +x gradlew
  
#temporary: fetch is faster than clone 
variables:
  GIT_STRATEGY: fetch

docker_images:
  stage: docker_images
  script: "./gradlew dockerImage"

unit_tests:
  stage: unit_tests
  script: "./gradlew test"
  artifacts:
    reports:
      junit: "*.xml"


integration_tests:
  stage: integration_tests
  script: "./gradlew integrationTest"
  
ChainWithDelayTest:
  stage: system_tests
  variables: 
    TEST: 'ChainWithDelayTest'
    STORAGE_TYPE: 'atmos,s3'
    RUN_MODE: 'local,distributed'
    CONCURRENCY: 'single,medium'
    ITEM_SIZE: 'medium'
  script:
    - "echo $TEST"
    - "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace"

CircularAppendTest:
  stage: system_tests
  variables:
    TEST: 'CircularAppendTest'
    STORAGE_TYPE: 'atmos,s3,fs'
    RUN_MODE: 'local,distributed'
    CONCURRENCY: 'low,medium'
    ITEM_SIZE: 'small,medium'
  script:
    - "echo $TEST"
    - "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace"

CircularReadLimitByTimeTest:
  stage: system_tests
  variables:
    TEST: 'CircularReadLimitByTimeTest'
    STORAGE_TYPE: 'fs,swift'
    RUN_MODE: 'local,distributed'
    CONCURRENCY: 'single,high'
    ITEM_SIZE: 'empty,medium'
  script:        
    - "echo $TEST"
    - "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace"    

UnlimitedCreateTest:
  stage: system_tests
  variables:
    TEST: 'UnlimitedCreateTest'
    STORAGE_TYPE: 'atmos,fs'
    RUN_MODE: 'local'
    CONCURRENCY: 'low'
    ITEM_SIZE: 'medium,huge'
  script: "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace"

CopyUsingInputPathTest: 
  stage: system_tests
  variables:
    TEST: 'CopyUsingInputPathTest'
    STORAGE_TYPE: 'fs'
    RUN_MODE: 'local'
    CONCURRENCY: 'medium'
    ITEM_SIZE: 'empty,small'
  script: "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace"

CreateLimitBySizeTest:
  stage: system_tests
  variables:
    TEST: 'CreateLimitBySizeTest'
    STORAGE_TYPE: 'fs'
    RUN_MODE: 'local'
    CONCURRENCY: 'low,high'
    ITEM_SIZE: 'small,medium'
  script: "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace"

MultipartCreateTest:
  stage: system_tests
  variables:
    TEST: 'MultipartCreateTest'
    STORAGE_TYPE: 's3,swift'
    RUN_MODE: 'local,distributed'
    CONCURRENCY: 'low,medium'
    ITEM_SIZE: 'large'
  script: "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace"

MultipleFixedUpdateAndSingleFixedReadTest:
  stage: system_tests
  variables:
    TEST: 'MultipleFixedUpdateAndSingleFixedReadTest'
    STORAGE_TYPE: 'fs,s3'
    RUN_MODE: 'local,distributed'
    CONCURRENCY: 'low,medium'
    ITEM_SIZE: 'small,medium'
  script: "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace"


MultipleRandomUpdateAndMultipleFixedReadTest:
  stage: system_tests
  variables:
    TEST: 'MultipleFixedUpdateAndSingleFixedReadTest'
    STORAGE_TYPE: 'fs,s3'
    RUN_MODE: 'local,distributed'
    CONCURRENCY: 'medium'
    ITEM_SIZE: 'small,medium'
  script: "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace"

ReadCustomContentVerificationFailTest:
  stage: system_tests
  variables:
    TEST: 'ReadCustomContentVerificationFailTest'
    STORAGE_TYPE: 'fs,s3,swift'
    RUN_MODE: 'local,distributed'
    CONCURRENCY: 'low,medium'
    ITEM_SIZE: 'small,medium'
  script: "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace"

ReadUsingVariablePathTest:
  stage: system_tests
  variables:
    TEST: 'ReadUsingVariablePathTest'
    STORAGE_TYPE: 'fs'
    RUN_MODE: 'local,distributed'
    CONCURRENCY: 'single,low,medium,high'
    ITEM_SIZE: 'empty,small'
  script: "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace" 
  
ReadVerificationAfterCircularUpdateTest:
  stage: system_tests
  variables:
    TEST: 'ReadVerificationAfterCircularUpdateTest'
    STORAGE_TYPE: 'fs'
    RUN_MODE: 'local'
    CONCURRENCY: 'low,medium'
    ITEM_SIZE: 'small'
  script: "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace" 

SingleFixedUpdateAndSingleRandomReadTest:
  stage: system_tests
  variables:
    TEST: 'SingleFixedUpdateAndSingleRandomReadTest'
    STORAGE_TYPE: 'fs,s3,swift'
    RUN_MODE: 'local,distributed'
    CONCURRENCY: 'single,low,medium,high'
    ITEM_SIZE: 'small,medium'
  script: "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace" 

SingleRandomUpdateAndMultipleRandomReadTest:
  stage: system_tests
  variables:
    TEST: 'SingleRandomUpdateAndMultipleRandomReadTest'
    STORAGE_TYPE: 'fs,s3,swift'
    RUN_MODE: 'local,distributed'
    CONCURRENCY: 'single,low,medium'
    ITEM_SIZE: 'small,medium'
  script: "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace" 

UnlimitedConcurrencyLimitByRateTest:
  stage: system_tests
  variables:
    TEST: 'UnlimitedConcurrencyLimitByRateTest'
    STORAGE_TYPE: 'atmos,fs,swift'
    RUN_MODE: 'local,distributed'
    CONCURRENCY: 'unlimited'
    ITEM_SIZE: 'small,medium,large'
  script: "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace"

WeightedLoadTest:
  stage: system_tests
  variables:
    TEST: 'WeightedLoadTest'
    STORAGE_TYPE: 'fs,s3,swift'
    RUN_MODE: 'distributed'
    CONCURRENCY: 'single,medium'
    ITEM_SIZE: 'empty,small'
  script: "./gradlew systemTest --tests com.emc.mongoose.system.$TEST --stacktrace"  



 


