image: java:8

stages:
  - unit_tests
  - integration_tests
  - docker_images
  - system_tests
  - deploy


before_script:
  - ls -l | grep gradlew
  - chmod +x gradlew

#temporary: fetch is faster than clone 
variables:
  GIT_STRATEGY: fetch

unit_tests:
  stage: unit_tests
  script: "./gradlew test"
  artifacts:
    reports:
      junit: "*.xml"


integration_tests:
  stage: integration_tests
  script: "./gradlew integrationTest"
  
system_tests1:
  variables: {TEST: TESTVALUE}
  script: "echo $TEST"