image: docker:stable

variables:
  LEGACY_SYSTEST_IMAGE_NAME: emcmongoose/mongoose-legacy-systest
  MONGOOSE_IMAGE_NAME: emcmongoose/mongoose
  ROBOTEST_IMAGE_NAME: emcmongoose/mongoose-robotest
  ROBOTEST_CONTAINER_WORKING_DIR: /root/mongoose

services:
  - docker:dind

stages:
  - build
  - test # simple unit/integration tests
  - deploy_docker_images
  - test_functional # functional containerized tests
  - deploy

build:
  image: openjdk:8-jdk-alpine
  stage: build
  script:
    - ./gradlew clean dist
  artifacts:
    paths:
      - build/libs/mongoose-*.jar

.test_java:
  image: openjdk:8-jdk-alpine
  stage: test

test_unit:
  extends: .test_java
  script:
  - ./gradlew test -PexcludeTests=**/TempInputFileSlicer*

test_integration:
  extends: .test_java
  script:
  - ./gradlew integrationTest

.deploy_docker_image:
  stage: deploy_docker_images
  script:
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
  - docker build -f docker/${DOCKERFILE} -t ${IMAGE_NAME}:${CI_COMMIT_SHA} .
  - docker push ${IMAGE_NAME}:${CI_COMMIT_SHA}

deploy_legacy_systest_image:
  extends: .deploy_docker_image
  variables:
    DOCKERFILE: Dockerfile.legacy-systest
    IMAGE_NAME: ${LEGACY_SYSTEST_IMAGE_NAME}

deploy_mongoose_image:
  extends: .deploy_docker_image
  variables:
    DOCKERFILE: Dockerfile
    IMAGE_NAME: ${MONGOOSE_IMAGE_NAME}

deploy_robotest_image:
  extends: .deploy_docker_image
  variables:
    DOCKERFILE: Dockerfile.robotest
    IMAGE_NAME: ${ROBOTEST_IMAGE_NAME}

.test_robot:
  image: ${ROBOTEST_IMAGE_NAME}:${CI_COMMIT_SHA}
  services:
    - docker:dind
  stage: test_functional
  variables:
    HOST_WORKING_DIR: ${CI_PROJECT_DIR}
    MONGOOSE_VERSION: ${CI_COMMIT_SHA}
  script:
    - docker --version
    - robot --outputdir ${ROBOTEST_CONTAINER_WORKING_DIR}/build/robotest --suite ${SUITE} --include ${TEST} ${ROBOTEST_CONTAINER_WORKING_DIR}/src/test/robot
    - rebot ${ROBOTEST_CONTAINER_WORKING_DIR}/build/robotest/output.xml
  artifacts:
    paths:
      - ${ROBOTEST_CONTAINER_WORKING_DIR}/build/robotest/*
    when: on_failure

test_api_remote_config:
  extends: .test_robot
  variables:
    SUITE: api.remote
    TEST: config

test_api_remote_run:
  extends: .test_robot
  variables:
    SUITE: api.remote
    TEST: run

test_api_storage_s3:
  extends: .test_robot
  variables:
    SUITE: api.storage
    TEST: s3

.test_system_legacy:
  image: ${LEGACY_SYSTEST_IMAGE_NAME}:${CI_COMMIT_SHA}
  services:
    - docker:dind
  stage: test_functional
  variables:
    MONGOOSE_VERSION: ${CI_COMMIT_SHA}
  script:
    - ./gradlew systemTest --tests com.emc.mongoose.system.${TEST}

.test_system_legacy_unstable:
  extends: .test_system_legacy
  retry: 2

test_legacy_circular_append:
  extends: .test_system_legacy
  variables:
    STORAGE_TYPE: atmos,s3,fs
    RUN_MODE: local,distributed
    CONCURRENCY: low,medium
    ITEM_SIZE: small
    TEST: CircularAppendTest

test_legacy_copy_using_input_path:
  extends: .test_system_legacy
  variables:
    TEST: CopyUsingInputPathTest
    STORAGE_TYPE: fs
    RUN_MODE: local
    CONCURRENCY: single,medium
    ITEM_SIZE: empty,small

test_legacy_multipart_create:
  extends: .test_system_legacy
  variables:
    TEST: MultipartCreateTest
    STORAGE_TYPE: s3,swift
    RUN_MODE: local,distributed
    CONCURRENCY: low,medium
    ITEM_SIZE: large

test_legacy_multiple_fixed_update_and_single_fixed_read:
  extends: .test_system_legacy
  variables:
    TEST: MultipleFixedUpdateAndSingleFixedReadTest
    STORAGE_TYPE: fs,s3
    RUN_MODE: local,distributed
    CONCURRENCY: low,medium
    ITEM_SIZE: small

test_legacy_multiple_random_update_and_multiple_fixed_read:
  extends: .test_system_legacy
  variables:
    TEST: MultipleRandomUpdateAndMultipleFixedReadTest
    STORAGE_TYPE: fs,s3
    RUN_MODE: local,distributed
    CONCURRENCY: medium
    ITEM_SIZE: small,medium

test_legacy_pipeline_with_delay:
  extends: .test_system_legacy
  variables:
    TEST: PipelineWithDelayTest
    STORAGE_TYPE: atmos,s3
    RUN_MODE: local,distributed
    CONCURRENCY: single,low,medium
    ITEM_SIZE: medium

test_legacy_read_custom_content_verification_fail:
  extends: .test_system_legacy
  variables:
    TEST: ReadCustomContentVerificationFailTest
    STORAGE_TYPE: fs,swift
    RUN_MODE: local,distributed
    CONCURRENCY: low,medium
    ITEM_SIZE: small,medium

test_legacy_read_using_variable_path:
  extends: .test_system_legacy
  variables:
    TEST: ReadUsingVariablePathTest
    STORAGE_TYPE: fs
    RUN_MODE: local,distributed
    CONCURRENCY: single,low,medium,high
    ITEM_SIZE: empty,small

test_legacy_single_fixed_update_and_single_random_read:
  extends: .test_system_legacy
  variables:
    TEST: SingleFixedUpdateAndSingleRandomReadTest
    STORAGE_TYPE: fs,swift
    RUN_MODE: local,distributed
    CONCURRENCY: single,medium
    ITEM_SIZE: small,medium

test_legacy_single_random_update_and_multiple_random_read:
  extends: .test_system_legacy
  variables:
    TEST: SingleRandomUpdateAndMultipleRandomReadTest
    STORAGE_TYPE: fs,swift
    RUN_MODE: local,distributed
    CONCURRENCY: low,medium
    ITEM_SIZE: small,medium

test_legacy_tls_read_using_input_file:
  extends: .test_system_legacy
  variables:
    TEST: TlsReadUsingInputFileTest
    STORAGE_TYPE: atmos,s3
    RUN_MODE: local,distributed
    CONCURRENCY: single,low
    ITEM_SIZE: empty,medium

test_legacy_unlimited_concurrency_limit_by_rate:
  extends: .test_system_legacy
  variables:
    TEST: UnlimitedConcurrencyLimitByRateTest
    STORAGE_TYPE: atmos,fs
    RUN_MODE: local,distributed
    CONCURRENCY: unlimited
    ITEM_SIZE: small,medium,large

test_legacy_unlimited_create:
  extends: .test_system_legacy
  variables:
    TEST: UnlimitedCreateTest
    STORAGE_TYPE: atmos,fs
    RUN_MODE: local,distributed
    CONCURRENCY: low
    ITEM_SIZE: medium,huge

test_legacy_weighted:
  extends: .test_system_legacy
  variables:
    TEST: WeightedLoadTest
    STORAGE_TYPE: fs,s3
    RUN_MODE: distributed
    CONCURRENCY: single,medium
    ITEM_SIZE: empty,small

test_legacy_circular_read_limit_by_time:
  extends: .test_system_legacy_unstable
  variables:
    TEST:  CircularReadLimitByTimeTest
    STORAGE_TYPE:  fs,swift
    RUN_MODE:  local,distributed
    CONCURRENCY:  single,high
    ITEM_SIZE:  empty,medium

test_legacy_create_limit_by_size:
  extends: .test_system_legacy_unstable
  variables:
    TEST: CreateLimitBySizeTest
    STORAGE_TYPE: fs
    RUN_MODE: local
    CONCURRENCY: low,high
    ITEM_SIZE: small,medium

test_legacy_read_verification_after_circular_update:
  extends: .test_system_legacy_unstable
  variables:
    STORAGE_TYPE: fs,s3
    RUN_MODE: local
    CONCURRENCY: low,medium
    ITEM_SIZE: small
    TEST: ReadVerificationAfterCircularUpdateTest

#CI_COMMIT_REF_NAME: branch/tag name
#CI_COMMIT_SHA: commit revision #
#CI_COMMIT_TAG: tag
