image: docker:stable

variables:
  MONGOOSE_IMAGE_NAME: emcmongoose/mongoose
  ROBOTEST_IMAGE_NAME: emcmongoose/mongoose-robotest
  ROBOTEST_CONTAINER_WORKING_DIR: /root/mongoose

services:
  - docker:dind

stages:
  - build
  - test # simple unit/integration tests
  - deploy_mongoose_image
  - deploy_robotest_image
  - test_functional # functional containerized tests
  - deploy

build:
  image: openjdk:8-jdk-alpine
  stage: build
  script:
    - ./gradlew clean dist
  artifacts:
    paths:
      - build/libs/mongoose-*.jar

test_unit:
  image: openjdk:8-jdk-alpine
  stage: test
  script:
  - ./gradlew test

test_integration:
  image: openjdk:8-jdk-alpine
  stage: test
  script:
  - ./gradlew integrationTest

deploy_mongoose_image:
  stage: deploy_mongoose_image
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - docker build -f docker/Dockerfile -t ${MONGOOSE_IMAGE_NAME}:${CI_COMMIT_SHA} .
    - docker push ${MONGOOSE_IMAGE_NAME}:${CI_COMMIT_SHA}

deploy_robotest_image:
  stage: deploy_robotest_image
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - docker build -f docker/Dockerfile.robotest -t ${ROBOTEST_IMAGE_NAME}:${CI_COMMIT_SHA} .
    - docker push ${ROBOTEST_IMAGE_NAME}:${CI_COMMIT_SHA}

test_api_remote_config:
  image: ${ROBOTEST_IMAGE_NAME}:${CI_COMMIT_SHA}
  stage: test_functional
  variables:
    HOST_WORKING_DRI: ${CI_PROJECT_DIR}
    MONGOOSE_VERSION: ${CI_COMMIT_SHA}
    SUITE: api.remote
    TEST: config
  script:
    - robot --outputdir ${ROBOTEST_CONTAINER_WORKING_DIR}/build/robotest --suite ${SUITE} --include ${TEST} ${ROBOTEST_CONTAINER_WORKING_DIR}/src/test/robot
    - rebot ${ROBOTEST_CONTAINER_WORKING_DIR}/build/robotest/output.xml

test_api_remote_run:
  image: ${ROBOTEST_IMAGE_NAME}:${CI_COMMIT_SHA}
  stage: test_functional
  variables:
    HOST_WORKING_DRI: ${CI_PROJECT_DIR}
    MONGOOSE_VERSION: ${CI_COMMIT_SHA}
    SUITE: api.remote
    TEST: run
  script:
  - robot --outputdir ${ROBOTEST_CONTAINER_WORKING_DIR}/build/robotest --suite ${SUITE} --include ${TEST} ${ROBOTEST_CONTAINER_WORKING_DIR}/src/test/robot
  - rebot ${ROBOTEST_CONTAINER_WORKING_DIR}/build/robotest/output.xml

test_api_storage_s3:
  image: ${ROBOTEST_IMAGE_NAME}:${CI_COMMIT_SHA}
  stage: test_functional
  variables:
    HOST_WORKING_DRI: ${CI_PROJECT_DIR}
    MONGOOSE_VERSION: ${CI_COMMIT_SHA}
    SUITE: api.storage
    TEST: s3
  script:
  - robot --outputdir ${ROBOTEST_CONTAINER_WORKING_DIR}/build/robotest --suite ${SUITE} --include ${TEST} ${ROBOTEST_CONTAINER_WORKING_DIR}/src/test/robot
  - rebot ${ROBOTEST_CONTAINER_WORKING_DIR}/build/robotest/output.xml

test_legacy_circular_append:
  stage: test_functional
  variables:
    STORAGE_TYPE: atmos,s3,fs
    RUN_MODE: local,distributed
    CONCURRENCY: low,medium
    ITEM_SIZE: small
    TEST: CircularAppendTest
  script:
    - ./gradlew systemTest --tests com.emc.mongoose.system.${TEST}

test_legacy_read_verification_after_circular_update:
  stage: test_functional
  variables:
    STORAGE_TYPE: fs,s3
    RUN_MODE: local
    CONCURRENCY: low,medium
    ITEM_SIZE: small
    TEST: ReadVerificationAfterCircularUpdateTest
  script:
    - ./gradlew systemTest --tests com.emc.mongoose.system.${TEST}
  retry: 2

#CI_COMMIT_REF_NAME: branch/tag name
#CI_COMMIT_SHA: commit revision #
#CI_COMMIT_TAG: tag
