image: java:8

stages:
  - system_tests
  - unit_tests
  - integration_tests
  - docker_images
  - deploy


before_script:
  - ls -l | grep gradlew
  - chmod +x gradlew

#temporary: fetch is faster than clone 
variables:
  GIT_STRATEGY: fetch

unit_tests:
  stage: unit_tests
  script: "./gradlew test"
  artifacts:
    reports:
      junit: "*.xml"


integration_tests:
  stage: integration_tests
  script: "./gradlew integrationTest"
  
system_tests1:
  stage: system_tests
  variables: 
    TEST: 'ChainWithDelayTest'
    STORAGE_TYPE: 'atmos,s3'
    RUN_MODE: 'local,distributed'
    CONCURRENCY: 'single,medium'
    ITEM_SIZE: 'medium'
  script:
    - "echo $TEST"
    - "./gradlew systemTest --tests com.emc.mongoose.system.$TEST"