image: java:8

before_script:
  - ls -l | grep gradlew
  - chmod +x gradlew

#temporary: fetch is faster than clone 
variables:
  GIT_STRATEGY: fetch

unit_tests:
  script: "./gradlew test"
  artifacts:
    reports:
      junit: "*.xml"


integration_tests:
  script: "./gradlew integrationTest"
  