image:
  - Visual Studio 2017

environment:
  HOME_DIR: C:\projects\mongoose
  PATH_TO_JAR: build\libs\mongoose-*.jar
  PATH_TO_ARTIFACTS: C:\projects\mongoose\build\robotest

build: off
build_script:
  - cmd: cd %HOME_DIR%
  - cmd: gradlew.bat clean dist

before_test:
  - ps: pip install -U virtualenv
  - ps: pip install -U requests
  - ps: pip install -U robotframework
  - ps: pip install -U robotframework-requests
  - ps: pip install -U robotframework-csvlibrary

test_script:
  - cmd: robot --outputdir %PATH_TO_ARTIFACTS% --suite api.storage --include "fs win" src\test\robot
#   - ps: java -jar $PATH_TO_JAR --storage-driver-type=dummy-mock --load-step-limit-time=20s

artifacts:
  - path: 'C:\projects\mongoose\build\robotest\*'



