image:
  - Visual Studio 2017

environment:
  HOME_DIR: C:\projects\mongoose
  PATH_TO_JAR: build\libs\mongoose-*.jar
  PATH_TO_ARTIFACTS: C:\projects\mongoose\build\robotest

build: off
build_script:
  - cmd: cd %HOME_DIR%
  - cmd: gradlew.bat clean dist

before_test:
  - ps: pip install -U virtualenv
  - ps: pip install -U requests
  - ps: pip install -U robotframework
  - ps: pip install -U robotframework-requests
  - ps: pip install -U robotframework-csvlibrary
  - cmd: set PYTHONPATH=%HOME_DIR%\src\test\robot\lib;C:\python27\lib\site-packages
  - cmd: mkdir %PATH_TO_ARTIFACTS%
  - cmd: type nul > %PATH_TO_ARTIFACTS%\report.html
  - cmd: type nul > %PATH_TO_ARTIFACTS%\output.xml
  - cmd: type nul > %PATH_TO_ARTIFACTS%\log.html

test_script:
  - cmd: IF EXIST %PATH_TO_ARTIFACTS%  ECHO %PATH_TO_ARTIFACTS% exists.
  - cmd: IF EXIST %PATH_TO_ARTIFACTS%\report.html  ECHO %PATH_TO_ARTIFACTS%\report.html exists.
  - cmd: IF EXIST %PATH_TO_ARTIFACTS%\log.html  ECHO %PATH_TO_ARTIFACTS%\log.html exists.
  - cmd: IF EXIST %PATH_TO_ARTIFACTS%\output.xml  ECHO %PATH_TO_ARTIFACTS%\output.xml exists.
  - cmd: robot --outputdir %PATH_TO_ARTIFACTS% --suite api.storage --include "fs win" src\test\robot
#   - ps: java -jar $PATH_TO_JAR --storage-driver-type=dummy-mock --load-step-limit-time=20s
after_test:
  - cmd: IF EXIST %PATH_TO_ARTIFACTS%  ECHO %PATH_TO_ARTIFACTS% exists.
  - cmd: type %PATH_TO_ARTIFACTS%\report.xml
#artifacts:
#- path: 'C:\projects\mongoose\build\robotest\*'
artifacts:
  - path: C:\projects\mongoose\build\robotest\
    name: Output
  - path: C:\projects\mongoose\build\robotest\log.html
    name: Log
  - path: 'C:\projects\mongoose\build\robotest\report.html'
    name: Report


