image:
  - Visual Studio 2017

environment:
  HOME_DIR: C:\projects\mongoose

build: off
build_script:
  - cmd: cd %HOME_DIR%
  - cmd: gradlew.bat clean dist

test_script:
  - cmd: java -jar build\libs\mongoose-4.1.0.jar --storage-driver-type=dummy-mock --load-step-limit-time=20s
